import os
HOST='0.0.0.0'; PORT=5000
BASE_DIR=os.path.dirname(os.path.abspath(__file__))
STATIC_DIR=os.path.join(BASE_DIR,'static'); TEMPLATES_DIR=os.path.join(BASE_DIR,'templates')
UPLOAD_FOLDER=os.path.join(STATIC_DIR,'uploads'); DATA_DIR=os.path.join(BASE_DIR,'data'); DATABASE_PATH=os.path.join(DATA_DIR,'streams.db')
FFMPEG_BINARY=os.environ.get('FFMPEG_BINARY','ffmpeg'); FFPROBE_BINARY=os.environ.get('FFPROBE_BINARY','ffprobe')
DEFAULT_VIDEO_CODEC='libx264'; DEFAULT_VIDEO_BITRATE='6000k'; DEFAULT_FPS=50; DEFAULT_RESOLUTION='1920x1080'; DEFAULT_PRESET='medium'; DEFAULT_GOP=100
DEFAULT_AUDIO_CODEC='aac'; DEFAULT_AUDIO_BITRATE='160k'; DEFAULT_SAMPLE_RATE=48000; DEFAULT_AUDIO_CHANNELS=2
DEFAULT_LOGO_POSITION='top-right'; DEFAULT_LOGO_SCALE=.15
MAX_RETRIES=5; RETRY_DELAY=3; HEARTBEAT_INTERVAL=5; FFMPEG_TIMEOUT=30; LOG_LINES=500; MAX_UPLOAD_MB=10
os.makedirs(UPLOAD_FOLDER,exist_ok=True); os.makedirs(DATA_DIR,exist_ok=True)
